[package]
name = "canny-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]          # required for wasm

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = { version = "0.1", optional = true }

# Image stack (all pure Rust → wasm‑safe)
image       = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
imageproc   = { version = "0.25", default-features = false }   # disable rayon → no thread issues

# Optional: faster grayscale conversion without floats
palette     = { version = "0.7", default-features = false, optional = true }
